INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Tony Stark','Iron Man',49,'USA','Avengers');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Steve Rogers','Capitão América',95,'USA','Avengers');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Thor Odinson','Thor',1500,'Asgard','Avengers');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Bruce Banner','Hulk',49,'USA','Avengers');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Peter Parker','Homem-Aranha',19,'USA','Avengers');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Kal-El','Super-Homem',35,'USA','Liga da Justiça');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Bruce Wayne','Batman',35,'USA','Liga da Justiça');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Diana Prince','Mulher-Maravilha',32,'Grécia','Liga da Justiça');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Barry Allen','Flash',25,'USA','Liga da Justiça');
INSERT INTO tb_hero(name,codename,age,country,team) VALUES('Arthur Curry','Aquaman',35,'Atlântida','Liga da Justiça');